import { z } from 'zod';

export enum AnalyticsMetrics {
  ACTIVE_USERS = 'active_users',
  WORKSPACE_ACTIVE_USERS = 'workspace_active_users',
  ELEMENTS_IN_WORKSPACE = 'elements_in_workspace',
  ACTIVE_WORKSPACES = 'active_workspaces',
  API_CALLS = 'api_calls',
  ACTIVE_COLLECTIONS = 'active_collections',
  RESPONSE_STATUS = 'response_status',
  PENDING_INVITES = 'pending_invites',
  NEEDS_ATTENTION = 'needs_attention',
  SUCCESS_RATE = 'success_rate',
  USER_REQUESTS = 'user_requests',
  USER_API_JOURNEY = 'user_api_journey',
  WORKSPACE_DISTRIBUTION = 'workspace_distribution',
  INTERNAL_WORKSPACE_DISTRIBUTION = 'internal_workspace_distribution',
  LICENSE_CONSUMPTION = 'license_consumption',
  MEMBERS = 'members',
  LAST_AUTOFLEX_CYCLE = 'last_autoflex_cycle',
  PARTNER_ENGAGEMENT_FUNNEL = 'partner_engagement_funnel',
  COLLECTION_ERROR_AGGREGATE = 'collection_error_aggregate',
  AGENT_MODE_USERS = 'agent_mode_users',
  NEW_VS_RETURNING_USERS = 'new_vs_returning_users',
  AGENT_MODE_SESSIONS = 'agent_mode_sessions',
  MESSAGES_SENT = 'messages_sent',
  CREDIT_USAGE = 'credit_usage',
  CREDIT_USAGE_BY_MODEL = 'credit_usage_by_model',
  USAGE_LEADERBOARD = 'usage_leaderboard',
  PEAK_ACTIVITY = 'peak_activity',
  ACTIVITY_DISTRIBUTION = 'activity_distribution',
  TOP_AGENT_MODELS_BY_USAGE = 'top_agent_models_by_usage',
  ENTITY_ACTIVITY = 'entity_activity',
  TOP_ENTITIES = 'top_entities',
  RUNS = 'runs',
  FUNCTIONAL_TEST_RUNS = 'functional_test_runs',
  PERFORMANCE_TEST_RUNS = 'performance_test_runs',
  MONITOR_RUNS = 'monitor_runs',
  FLOW_EXECUTIONS = 'flow_executions',
  PVT_NETWORK = 'pvt_network',
  PARTNER = 'partner',
  PUBLIC_ = 'public',
  WORKSPACE_ACTIVITY = 'workspace_activity',
  MEMBERS_OVERTIME = 'members_overtime',
  MEMBER_INVITES = 'member_invites',
  INVITES_SENT = 'invites_sent',
  INVITES_ACCEPTED = 'invites_accepted',
}
