import { z } from 'zod';

export const analyticsMetrics = z.union([
  z.literal('active_users'),
  z.literal('workspace_active_users'),
  z.literal('elements_in_workspace'),
  z.literal('active_workspaces'),
  z.literal('api_calls'),
  z.literal('active_collections'),
  z.literal('response_status'),
  z.literal('pending_invites'),
  z.literal('needs_attention'),
  z.literal('success_rate'),
  z.literal('user_requests'),
  z.literal('user_api_journey'),
  z.literal('workspace_distribution'),
  z.literal('internal_workspace_distribution'),
  z.literal('license_consumption'),
  z.literal('members'),
  z.literal('last_autoflex_cycle'),
  z.literal('partner_engagement_funnel'),
  z.literal('collection_error_aggregate'),
  z.literal('agent_mode_users'),
  z.literal('new_vs_returning_users'),
  z.literal('agent_mode_sessions'),
  z.literal('messages_sent'),
  z.literal('credit_usage'),
  z.literal('credit_usage_by_model'),
  z.literal('usage_leaderboard'),
  z.literal('peak_activity'),
  z.literal('activity_distribution'),
  z.literal('top_agent_models_by_usage'),
  z.literal('entity_activity'),
  z.literal('top_entities'),
  z.literal('runs'),
  z.literal('functional_test_runs'),
  z.literal('performance_test_runs'),
  z.literal('monitor_runs'),
  z.literal('flow_executions'),
  z.literal('pvt_network'),
  z.literal('partner'),
  z.literal('public'),
  z.literal('workspace_activity'),
]);

export type AnalyticsMetrics = z.infer<typeof analyticsMetrics>;
