import { z } from 'zod';

export enum CreateAccessRequestRole {
  TEAM_MANAGER = 'TEAM_MANAGER',
  TEAM_DEVELOPER = 'TEAM_DEVELOPER',
  TEAM_GUEST_DEVELOPER = 'TEAM_GUEST_DEVELOPER',
  TEAM_GUEST_VIEWER = 'TEAM_GUEST_VIEWER',
  TEAM_PARTNER_MANAGER = 'TEAM_PARTNER_MANAGER',
  TEAM_PARTNER_LEAD = 'TEAM_PARTNER_LEAD',
  TEAM_GUEST = 'TEAM_GUEST',
  TEAM_PARTNER = 'TEAM_PARTNER',
  TEAM_COMMUNITY_MANAGER = 'TEAM_COMMUNITY_MANAGER',
}
