name: Publish to GitHub Packages

on:
  push:
    branches: ['main']

jobs:
  publish:
    uses: ./.github/workflows/_publish.yml
    permissions:
      contents: read
      packages: write
    with:
      registry-url: 'https://npm.pkg.github.com'
      scope: '@postmanlabs'
      package-name: '@postmanlabs/api-sdk'
      use-oidc: false
    secrets:
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
